export const masterTypeConfig = {
  shift: {
    label: 'Shift',
    fields: ['name'],
    displayFields: { name: 'Shift Name' },
    tableColumns: ['name', 'active'],
    columnLabels: { name: 'Shift Name', active: 'Status' },
    parent: null,
    description: 'Work shifts (Morning, Evening, Night)',
    color: 'blue',
    icon: '🕐',
  },
  line: {
    label: 'Production Line',
    fields: ['name', 'code'],
    displayFields: { name: 'Line Name', code: 'Line Code' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Line', code: 'Code', active: 'Status' },
    parent: null,
    description: 'Production lines (Line 1–5 and Line F)',
    color: 'purple',
    icon: '🏭',
  },
  machine: {
    label: 'Machine',
    fields: ['name', 'code', 'lineId'],
    displayFields: { name: 'Machine Name', code: 'Machine Code', lineId: 'Production Line' },
    tableColumns: ['name', 'code', 'lineId', 'active'],
    columnLabels: { name: 'Machine', code: 'Code', lineId: 'Line', active: 'Status' },
    parent: 'line',
    description: 'Machines on production lines',
    color: 'orange',
    icon: '⚙️',
  },
  process: {
    label: 'Process',
    fields: ['name', 'code', 'machineId'],
    displayFields: { name: 'Process Name', code: 'Process Code', machineId: 'Machine' },
    tableColumns: ['name', 'code', 'machineId', 'active'],
    columnLabels: { name: 'Process', code: 'Code', machineId: 'Machine', active: 'Status' },
    parent: 'machine',
    description: 'Manufacturing processes per machine',
    color: 'pink',
    icon: '⚡',
  },
  operator: {
    label: 'Operator',
    fields: ['name', 'code'],
    displayFields: { name: 'Operator Name', code: 'Employee ID' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Name', code: 'Employee ID', active: 'Status' },
    parent: null,
    description: 'Factory operators',
    color: 'cyan',
    icon: '👤',
  },
};
