export const masterTypeConfig = {
  shift: {
    label: 'Shift',
    fields: ['name'],
    displayFields: { name: 'Shift Name' },
    tableColumns: ['name', 'active'],
    columnLabels: { name: 'Shift Name', active: 'Status' },
    parent: null,
    description: 'Work shifts (Morning, Evening, Night)',
    color: 'blue',
    icon: '🕐',
  },
  department: {
    label: 'Department',
    fields: ['name', 'code'],
    displayFields: { name: 'Department Name', code: 'Department Code' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Name', code: 'Code', active: 'Status' },
    parent: null,
    description: 'Departments within factory',
    color: 'green',
    icon: '🏢',
  },
  line: {
    label: 'Production Line',
    fields: ['name', 'code', 'departmentId'],
    displayFields: { name: 'Line Name', code: 'Line Code', departmentId: 'Department' },
    tableColumns: ['name', 'code', 'departmentId', 'active'],
    columnLabels: { name: 'Line', code: 'Code', departmentId: 'Department', active: 'Status' },
    parent: 'department',
    description: 'Production lines under departments',
    color: 'purple',
    icon: '🏭',
  },
  machine: {
    label: 'Machine',
    fields: ['name', 'code', 'lineId'],
    displayFields: { name: 'Machine Name', code: 'Machine Code', lineId: 'Production Line' },
    tableColumns: ['name', 'code', 'lineId', 'active'],
    columnLabels: { name: 'Machine', code: 'Code', lineId: 'Line', active: 'Status' },
    parent: 'line',
    description: 'Machines on production lines',
    color: 'orange',
    icon: '⚙️',
  },
  process: {
    label: 'Process',
    fields: ['name', 'code', 'machineId'],
    displayFields: { name: 'Process Name', code: 'Process Code', machineId: 'Machine' },
    tableColumns: ['name', 'code', 'machineId', 'active'],
    columnLabels: { name: 'Process', code: 'Code', machineId: 'Machine', active: 'Status' },
    parent: 'machine',
    description: 'Manufacturing processes per machine',
    color: 'pink',
    icon: '⚡',
  },
  operator: {
    label: 'Operator',
    fields: ['name', 'code', 'departmentId'],
    displayFields: { name: 'Operator Name', code: 'Employee ID', departmentId: 'Department' },
    tableColumns: ['name', 'code', 'departmentId', 'active'],
    columnLabels: { name: 'Name', code: 'Employee ID', departmentId: 'Department', active: 'Status' },
    parent: 'department',
    description: 'Factory operators by department',
    color: 'cyan',
    icon: '👤',
  },
  product: {
    label: 'Product',
    fields: ['name', 'code'],
    displayFields: { name: 'Product Name', code: 'Product Code' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Product', code: 'Code', active: 'Status' },
    parent: null,
    description: 'Products manufactured',
    color: 'indigo',
    icon: '📦',
  },
  defectType: {
    label: 'Defect Type',
    fields: ['name', 'code'],
    displayFields: { name: 'Defect Type Name', code: 'Type Code' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Type', code: 'Code', active: 'Status' },
    parent: null,
    description: 'Types of product defects (Critical, Major, Minor)',
    color: 'red',
    icon: '❌',
  },
  downtimeReason: {
    label: 'Downtime Reason',
    fields: ['name', 'code'],
    displayFields: { name: 'Reason Name', code: 'Reason Code' },
    tableColumns: ['name', 'code', 'active'],
    columnLabels: { name: 'Reason', code: 'Code', active: 'Status' },
    parent: null,
    description: 'Reasons for production downtime (Power, Maintenance, etc.)',
    color: 'amber',
    icon: '⏸️',
  },
};
